// <auto-generated />
using System;
using FinalProjectGroup2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectGroup2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241201210427_ZBInitial")]
    partial class ZBInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectGroup2.Models.CollegeTeamMM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FootballTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollegeTeam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cleveland",
                            FootballTeam = "Ohio State",
                            FullName = "Marian Muntean",
                            Mascot = "Brutus Buckeye"
                        },
                        new
                        {
                            Id = 2,
                            City = "Ann Arbor",
                            FootballTeam = "University of Michigan",
                            FullName = "Xander Marsden",
                            Mascot = "Biff, the Michigan Wolverine"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cincinnati",
                            FootballTeam = "University of Cincinnati",
                            FullName = "Eli Cagle",
                            Mascot = "the Bearcat"
                        },
                        new
                        {
                            Id = 4,
                            City = "Athens",
                            FootballTeam = "Ohio University",
                            FullName = "Zachary Baker",
                            Mascot = "Rufus, the Bobcat"
                        },
                        new
                        {
                            Id = 5,
                            City = "Lexington",
                            FootballTeam = "University of Kentucky",
                            FullName = "Kevin Stradman",
                            Mascot = "the Wildcat"
                        });
                });

            modelBuilder.Entity("FinalProjectGroup2.Models.SpaceShuttleZB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstLaunch")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLaunch")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShuttleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalMissions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpaceShuttle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstLaunch = new DateTime(1981, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLaunch = new DateTime(2003, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShuttleName = "Columbia",
                            TotalMissions = 28
                        },
                        new
                        {
                            Id = 2,
                            FirstLaunch = new DateTime(1983, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLaunch = new DateTime(1986, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShuttleName = "Challenger",
                            TotalMissions = 10
                        },
                        new
                        {
                            Id = 3,
                            FirstLaunch = new DateTime(1984, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLaunch = new DateTime(2011, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShuttleName = "Discovery",
                            TotalMissions = 39
                        },
                        new
                        {
                            Id = 4,
                            FirstLaunch = new DateTime(1985, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLaunch = new DateTime(2011, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShuttleName = "Atlantis",
                            TotalMissions = 33
                        },
                        new
                        {
                            Id = 5,
                            FirstLaunch = new DateTime(1992, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLaunch = new DateTime(2011, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShuttleName = "Endeavour",
                            TotalMissions = 25
                        });
                });

            modelBuilder.Entity("FinalProjectGroup2.Models.TeamMemberEC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Xander Marsden",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2000, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Eli Cagle",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1982, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Marian Muntean",
                            YearInProgram = "Sophmore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2004, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Zachary Baker",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "??",
                            FullName = "Kevin Stradman",
                            YearInProgram = "??"
                        });
                });

            modelBuilder.Entity("FinalProjectGroup2.Models.VidGameXM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Xander Marsden",
                            GameName = "HellDivers 2",
                            InitialDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "PC"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Eli Cagle",
                            GameName = "Call of Duty",
                            InitialDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Xbox"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Marian Muntean",
                            GameName = "Until Dawn",
                            InitialDate = new DateTime(2021, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "PlayStation 4"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Zachary Baker",
                            GameName = "Phasmaphobia",
                            InitialDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "Xbox"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Kevin Stradman",
                            GameName = "Sonic Heroes",
                            InitialDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "GameCube"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "John Doe",
                            GameName = "Astro Bot",
                            InitialDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Platform = "PlayStation 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
